CREATE PROC GetAppointmentList
AS
BEGIN
	SELECT A.*, DEP.TITLE AS Department,P.FIRSTNAME,P.LASTNAME
	FROM 
		APPOINTMENT AS A 
		JOIN DOCTOR AS DOC
		ON DOC.M_S_N = A.DOCTORID
		JOIN DEPARTMENT AS DEP
		ON DEP.ID = DOC.DEPARTMENTID
		JOIN PERSON AS P
		ON P.NATIONALCODE = DOC.PersonId
END;