CREATE PROC GetDoctorsList
AS
BEGIN
	SELECT DOC.M_S_N,DOC.RATE,P.FIRSTNAME,P.LASTNAME,DEP.TITLE AS Department,DOC.RESUME_ AS Resume,p.NATIONALCODE  as PersonId
	FROM
		DEPARTMENT AS DEP
		JOIN
		DOCTOR AS DOC ON DOC.DEPARTMENTID = DEP.ID
		JOIN
		PERSON AS P ON P.NATIONALCODE = DOC.PersonId
END;