CREATE PROC GetPatientList
AS
BEGIN 
	SELECT PAT.BIRTH_DATE,PAT.BLOOD_TYPE,PAT.GENDER,PAT.ID,P.FIRSTNAME,P.LASTNAME
	FROM 
		PATIENT AS PAT
		JOIN
		PERSON AS P
		ON P.NATIONALCODE = PAT.NATIONALCODE
END;