CREATE PROC InsertAppointment
	@ID INT,
	@DOCTORID INT,
	@DESCRIPTIONN NVARCHAR(MAX),
	@TIME_ DATETIME
AS
BEGIN
	INSERT INTO APPOINTMENT(DOCTORID,DESCRIPTIONN,TIME_)
	OUTPUT inserted.ID
	VALUES(@DOCTORID,@DESCRIPTIONN,@TIME_)
END;