CREATE PROC InsertPatient
	@BLOOD_TYPE NVARCHAR(5),
	@NATIONALCODE NVARCHAR(50),
	@GENDER BIT,
	@BIRTH_DATE DATE
AS
BEGIN
	INSERT INTO PATIENT(BLOOD_TYPE,NATIONALCODE,GENDER,BIRTH_DATE)
	OUTPUT inserted.ID
	VALUES(@BLOOD_TYPE,@NATIONALCODE,@GENDER,@BIRTH_DATE)
END;