CREATE PROC UpdatePatient
	@ID INT,
	@GENDER BIT,
	@BLOOD_TYPE NVARCHAR(5),
	@BIRTH_DATE DATE
AS
BEGIN
	UPDATE PATIENT
	SET
	GENDER = @GENDER,
	BLOOD_TYPE= @BLOOD_TYPE,
	BIRTH_DATE = @BIRTH_DATE
	WHERE ID = @ID
END;