CREATE PROC UpdateDoctor
	@M_S_N INT,
	@DEPARTMENTID INT,
	@Rate INT,
	@RESUME_ NVARCHAR(MAX)
AS
BEGIN
	UPDATE DOCTOR
	SET
	DEPARTMENTID = @DEPARTMENTID,
	RESUME_ = @RESUME_,
	RATE = @Rate
	WHERE M_S_N = @M_S_N
END;